Devex 973
onelogin/postman-collections pull request #2
Opened 2022-06-08 20:22 UTC by Jmfwolf

This is a complete removal of the old postman-collection system. This is the first step in automating the synchronization of collections across Github, Postman, and Onelogin Developer Documentation.

This is setting our Github Repo as the authoritative Postman Collection.

2022-06-09 16:27 UTC, bzvestey requested changes
A couple of items here:
1. Please always add the link to the Jira in the ticket. I should have added more to our conversation about this earlier this week, sorry about that.
2. Have you talked with QE and seen if they are using any of these collections for their automated testing?
3. Is this more of a reorganization of the postman collections? or are there actually added/deleted ones?
4. Are there additional steps that are going to be done as part of this task?
5. Since I don't see any information about it, do can you share a more in depth description of what we are trying to do with these changes? Or bring in someone who can describe it more?

2022-06-09 16:28 UTC, bzvestey commented
Overall I have no issues with the change, I just like having an understanding of the reasoning behind them.

2022-06-09 17:04 UTC, Jmfwolf commented
Thank you for the feedback!
1. The jira ticket: https://onelogin2.atlassian.net/browse/DEVEX-973
2. Erik and I spoke to Wendy and are coordinating that effort to make sure they have what they need.
3. This is deleting the old organization and starting over with the best of what we had before. This ticket is part of a much larger epic. I made this ticket to get specific issues handled that weren't explicitly stated.
4. In this task, there should not be additional steps.
5. There is more about the general idea, https://onelogin2.atlassian.net/browse/DEVEX-969 I am not sure if it is explicit

2022-06-09 19:53 UTC, bzvestey commented
So I talked with @eriktalvi over lunch some, and he said that he would get the ticket updated with more information around why we are doing this. It is important to have a paper trail around why we do something, in case someone needs to go back and figure out what is going on.

You mentioned an epic that this is all part of, is that DEVEX-969? or is there another epic?

2022-06-14 17:15 UTC, Jmfwolf commented
Changed to one mono collection that contains all versions per @mrmoss specifications. The other version folders are for anyone that would like to use just a single collection still

2022-06-20 23:16 UTC, bzvestey approved these changes

2022-06-21 16:19 UTC, mrmoss commented
I'd remove all empty v1/v2 folders (if there isnt a version, don't list).

At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.

There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, etc...).

2022-06-21 16:24 UTC, mrmoss commented
> I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> 
> At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> 
> There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).

Correction on app rules - I see them under apps v2. I'd break this out into `App Rules` with its own versioning since it is its own service and would be updated outside of the apps service.

2022-06-26 03:42 UTC, Jmfwolf commented
> I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> 
> At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> 
> There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).

According to the documentation that I can find, those don't exist. This version control issue can be addressed through api automation.

> > I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> > At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> > There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).
> 
> Correction on app rules - I see them under apps v2. I'd break this out into `App Rules` with its own versioning since it is its own service and would be updated outside of the apps service.

Is this something we want to change on this ticket or another one?

2022-06-27 16:02 UTC, eriktalvi reviewed
You deleted a many more collections in this PR than exist within the mono collection. I'd go back through and double check that a deleted collection got added to the collection or that it did not need to be (such as the Accounts API).

2022-06-27 16:02 UTC, eriktalvi commented on mono_collection/mono_collection.postman_collection.json
> +		"name": "mono_collection",
mono collection is useful for us internally, but this will be used by customers externally. Below is only a suggestion on what to name the collection:

```suggestion
		"name": "OneLogin API Definitive",
```

2022-06-27 16:02 UTC, eriktalvi commented on mono_collection/mono_collection.postman_collection.json
> +					"name": "V1",
Not sure if this was already suggested, but drop empty versioning. Don't need a user to click 'v1' only to be disappointed its empty.

2022-06-27 16:02 UTC, eriktalvi commented on mono_collection/mono_collection.postman_collection.json
> +					"name": "V1",
empty version

2022-06-27 16:06 UTC, eriktalvi commented
> > I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> > At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> > There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).
> 
> According to the documentation that I can find, those don't exist. This version control issue can be addressed through api automation.

So our documentation isn't great on this. Looking at the code is valuable here. Additionally some of these are listed on the API Reference -  for example api/2/users is [here](https://developers.onelogin.com/api-docs/2/users/list-users). Alicia's spreadsheet can also be used as a way to verify what should be in the monocollection.

2022-06-27 18:15 UTC, mrmoss commented
> > I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> > At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> > There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).
> 
> According to the documentation that I can find, those don't exist. This version control issue can be addressed through api automation.
> 
> > > I'd remove all empty v1/v2 folders (if there isnt a version, don't list).
> > > At least on the OAuth 2.0 folder, v1 and v2 are the same. I'd remove v2.
> > > There are also some missing versions (ex: /api/2/roles and /api/2/users, /api/2/mfa, /api/2/apps/*/rules, etc...).
> > 
> > 
> > Correction on app rules - I see them under apps v2. I'd break this out into `App Rules` with its own versioning since it is its own service and would be updated outside of the apps service.
> 
> Is this something we want to change on this ticket or another one?

What are you using for documentation? They are on the API page?
![Screen Shot 2022-06-27 at 11 14 31 AM](https://user-images.githubusercontent.com/1828563/176008424-ad5667c9-b6f6-47b7-80cf-741979597d43.png)

2022-07-06 19:58 UTC, bzvestey reviewed
Just one last empty folder, and then I call it good.

2022-07-06 19:58 UTC, bzvestey commented on mono_collection/OneLogin API Definitive.postman_collection.json
> +													"        // case \"Chr
Please remove the empty folder.

2022-07-06 19:58 UTC, bzvestey commented on mono_collection/OneLogin API Definitive.postman_collection.json
> +													"        // case \"Chr
This is for Smart MFA/v1

2022-07-06 20:47 UTC, merged